package eu.winwinit.bcc.entities;
// Generated 2-ott-2019 9.39.22 by Hibernate Tools 4.3.5.Final

import java.util.ArrayList;
import java.util.Date;
import java.util.List;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Filiali generated by hbm2java
 */
@Entity
@Table(name = "filiali")
public class Filiale implements java.io.Serializable {

	private Integer id;
	private String nome;
	private Integer codice;
	private String cab;
	private Date lastModify;
	private List<Cliente> clienti = new ArrayList<Cliente>();
	private List<Utente> utenti = new ArrayList<Utente>();

	public Filiale() {
	}

	public Filiale(String nome, String cab, Integer codice) {
		this.nome = nome;
		this.cab = cab;
		this.codice = codice;
	}

//	public Filiale(String nome, Integer codice, String cab, ArrayList<Cliente> clienti, ArrayList<Utente> utenti) {
//		this.nome = nome;
//		this.codice = codice;
//		this.cab = cab;
//		this.clienti = clienti;
//		this.utenti = utenti;
//	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@Column(name = "nome", nullable = false, length = 40)
	public String getNome() {
		return this.nome;
	}

	public void setNome(String nome) {
		this.nome = nome;
	}

	@Column(name = "codice")
	public Integer getCodice() {
		return this.codice;
	}

	public void setCodice(Integer codice) {
		this.codice = codice;
	}

	@Column(name = "cab", nullable = false, length = 5)
	public String getCab() {
		return this.cab;
	}

	public void setCab(String cab) {
		this.cab = cab;
	}

	@Column(name = "last_modify")
	public Date getLastModify() {
		return lastModify;
	}

	public void setLastModify(Date lastModify) {
		this.lastModify = lastModify;
	}


//	@OneToMany(fetch = FetchType.LAZY, mappedBy = "filiali")
//	public ArrayList<Cliente> getClienti() {
//		return this.clienti;
//	}
//
//	public void setClienti(ArrayList<Cliente> clienti) {
//		this.clienti = clienti;
//	}
//
//	@OneToMany(fetch = FetchType.LAZY, mappedBy = "filiali")
//	public ArrayList<Utente> getUtenti() {
//		return this.utenti;
//	}
//
//	public void setUtenti(ArrayList<Utente> utenti) {
//		this.utenti = utenti;
//	}

}
