package eu.winwinit.bcc.entities;
// Generated 2-ott-2019 9.39.22 by Hibernate Tools 4.3.5.Final

import java.util.ArrayList;
import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.UniqueConstraint;

import com.fasterxml.jackson.annotation.JsonIgnore;

/**
 * RuoliUtenti generated by hbm2java
 */
@Entity
@Table(name = "ruoli_utenti", uniqueConstraints = @UniqueConstraint(columnNames = "ruolo"))
public class RuoloUtente implements java.io.Serializable {

	private Integer id;
	private String ruolo;
	private Utente utenti;
	private Date lastModify;
	
//	private ArrayList<Utente> utenti = new ArrayList<Utente>();

	public RuoloUtente() {
	}

	public RuoloUtente(String ruolo) {
		this.ruolo = ruolo;
	}

//	public RuoloUtente(String ruolo, ArrayList<Utente> utenti) {
//		this.ruolo = ruolo;
//		this.utenti = utenti;
//	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@Column(name = "ruolo", unique = true, nullable = false, length = 20)
	public String getRuolo() {
		return this.ruolo;
	}

	public void setRuolo(String ruolo) {
		this.ruolo = ruolo;
	}

	@JsonIgnore
	@ManyToOne(fetch = FetchType.EAGER)
	@JoinColumn(name = "user_modify", nullable = false)
	public Utente getUtenti() {
		return utenti;
	}

	public void setUtenti(Utente utenti) {
		this.utenti = utenti;
	}

	@Column(name = "last_modify")
	public Date getLastModify() {
		return lastModify;
	}

	public void setLastModify(Date lastModify) {
		this.lastModify = lastModify;
	}


//	@OneToMany(fetch = FetchType.LAZY, mappedBy = "ruoliUtenti")
//	public ArrayList<Utente> getUtenti() {
//		return this.utenti;
//	}
//
//	public void setUtenti(ArrayList<Utente> utenti) {
//		this.utenti = utenti;
//	}

}
