package eu.winwinit.bcc.entities;
// Generated 2-ott-2019 9.39.22 by Hibernate Tools 4.3.5.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;

import java.util.Date;

import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.UniqueConstraint;

import lombok.Data;

/**
 * Utenti generated by hbm2java
 */
@Data
@Entity
@Table(name = "utenti", uniqueConstraints = @UniqueConstraint(columnNames = "username"))
public class Utente implements java.io.Serializable {

	private Integer id;
	private Filiale filiali;
	private RuoloUtente ruoliUtenti;
	private String username;
	private String nome;
	private String cognome;
	private String password;
	private Boolean statoAttivo;
	private Boolean cambioPassword;
	private Date lastModify;

	public Utente() {
	}

	public Utente(Filiale filiali, RuoloUtente ruoliUtenti, String username, String password) {
		this.filiali = filiali;
		this.ruoliUtenti = ruoliUtenti;
		this.username = username;
		this.password = password;
	}

	public Utente(Filiale filiali, RuoloUtente ruoliUtenti, String username, String nome, String cognome,
			String password, Boolean statoAttivo, Boolean cambioPassword) {
		this.filiali = filiali;
		this.ruoliUtenti = ruoliUtenti;
		this.username = username;
		this.nome = nome;
		this.cognome = cognome;
		this.password = password;
		this.statoAttivo = statoAttivo;
		this.cambioPassword = cambioPassword;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.EAGER)
	@JoinColumn(name = "filiale", nullable = false)
	public Filiale getFiliali() {
		return this.filiali;
	}

	public void setFiliali(Filiale filiali) {
		this.filiali = filiali;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "ruolo", nullable = false)
	public RuoloUtente getRuoliUtenti() {
		return this.ruoliUtenti;
	}

	public void setRuoliUtenti(RuoloUtente ruoliUtenti) {
		this.ruoliUtenti = ruoliUtenti;
	}

	@Column(name = "username", unique = true, nullable = false, length = 20)
	public String getUsername() {
		return this.username;
	}

	public void setUsername(String username) {
		this.username = username;
	}

	@Column(name = "nome", length = 30)
	public String getNome() {
		return this.nome;
	}

	public void setNome(String nome) {
		this.nome = nome;
	}

	@Column(name = "cognome", length = 30)
	public String getCognome() {
		return this.cognome;
	}

	public void setCognome(String cognome) {
		this.cognome = cognome;
	}

	@Column(name = "password", nullable = false, length = 20)
	public String getPassword() {
		return this.password;
	}

	public void setPassword(String password) {
		this.password = password;
	}

	@Column(name = "stato_attivo")
	public Boolean getStatoAttivo() {
		return this.statoAttivo;
	}

	public void setStatoAttivo(Boolean statoAttivo) {
		this.statoAttivo = statoAttivo;
	}

	@Column(name = "cambio_password")
	public Boolean getCambioPassword() {
		return this.cambioPassword;
	}

	public void setCambioPassword(Boolean cambioPassword) {
		this.cambioPassword = cambioPassword;
	}

	@Column(name = "last_modify")
	public Date getLastModify() {
		return lastModify;
	}

	public void setLastModify(Date lastModify) {
		this.lastModify = lastModify;
	}

}
